name: Terraform CI/CD Pipeline

on:
  # schedule:
  #   - cron: '0 14 * * *'     # Cron job to run at 2:00 PM UTC every day
  push:
    branches: [ main, dev ]
    # branches: 
      # - main
      # - dev
    # workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab - ONLY MANUAL TRIGGER — no auto-run!

env:
  AWS_REGION: eu-west-2
  TF_VERSION: "1.15.1"
  TF_WORKSPACE: dev
  WORKING_DIR: ./AWS_TERRAFORM

  # push:
  #   branches:
  #     - main 

jobs:
  terraform-plan:  # Plan job runs on both PRs and on any push
    runs-on: ubuntu-latest-8-cores
    # runs-on: self-hosted  #  picks any self-hosted runner (repo → Settings → Actions → Runners)
    # defaults:
    #   run:
    #     working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Format Check
      #   run: terraform fmt -check

      # - name: Terraform Validate
      #   run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -parallelism=40 \
            -refresh=false \
            -out=tfplan \
            -var-file=environments/${{ env.TF_WORKSPACE }}.tfvars  
        # run: terraform plan 

  terraform-apply:   # Separate job for apply, triggered only on push to main
    needs: terraform-plan
    runs-on: ubuntu-latest-8-cores
    # defaults:
    #   run:
    #     working-directory: ${{ env.WORKING_DIR }}
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply \
            -parallelism=40 \
            -refresh=true \
            -auto-approve \
            -var-file=environments/${{ env.TF_WORKSPACE }}.tfvars

      # - name: Terraform Destroy
      #   if: github.ref == 'refs/heads/dev' 
      #   run: |
      #     terraform destroy \
      #     -parallelism=40 \
      #     -var-file=environments/dev.tfvars




   
# jobs:
#   deploy:
#     runs-on: self-hosted   #  picks any self-hosted runner
#     # OR specific label: runs-on: [self-hosted, linux, terraform]
#     permissions:
#       id-token: write            #  allows OIDC token generation 
#       contents: read
#     steps:
#       - uses: actions/checkout@v4
#       - name: Configure AWS OIDC
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::123456789123:role/github-actions-deploy
#           aws-region: eu-west-2

#       - run: terraform init
#       - run: terraform workspace select dev
#       - run: terraform apply -auto-approve